apiVersion: apps/v1
kind: Deployment
metadata:
  name: Tetrics
  namespace: default
  labels:
    app: Tetrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Tetrics
  template:
    metadata:
      labels:
        app: Tetrics
    spec:
      containers:
        - name: Tetrics
          image: 811545553615.dkr.ecr.ap-south-1.amazonaws.com/tetris:latest
          ports:
           - containers: 80
          resources:
            request:
              memory: "64Mi"
              cpu: "100m"
            limit: 
              memory: "128Mi"
              cpu: "200m"

