apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetrics
  namespace: default
  labels:
    app: tetrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetrics
  template:
    metadata:
      labels:
        app: tetrics
    spec:
      containers:
        - name: tetrics
          image: 811545553615.dkr.ecr.ap-south-1.amazonaws.com/tetris:latest
          ports:
           - containerPort: 80
          resources:
            request:
              memory: "64Mi"
              cpu: "100m"
            limit: 
              memory: "128Mi"
              cpu: "200m"

