apiVersion: v1 
kind: Service
metadata:
  name: tetris-service
  namespace: default
spec:
  selector:
    app: tetrics
  type: LoadBalancer
  ports:  
    - Portocol: TCP
      port: 80
      targetPort: 80