apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Tetrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akshaybk85/Tetris-github-actions.git
    targerRevision: main
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: 
    automated: 
      prune:
      selHeal: true
      
